import type { Metadata } from 'next'
import { Toaster } from 'sonner'
import localFont from 'next/font/local'
import './globals.css'
import Header from './components/header'
import { DefaultProviders } from './components/default-providers'

const coolvetica = localFont({
  src: '../fonts/Garet-Book.ttf',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={coolvetica.className}>
        <DefaultProviders>
          <Header />
          {children}
          <Toaster />
        </DefaultProviders>
      </body>
    </html>
  )
}
